### ISSUE TITLE
Strip null byte

### ISSUE THREAD

**Issue by mojotalantikite** [pin/tftp#1]
I was just playing around with your library and ran into a small issue when using the default tftp program in OS X 10.10.3. It looks like there is a \x00 byte that gets passed into the filename parameter, which causes a read error if you attempt to do an os.Open(filename) in a tftp ReadHandler. 

I fixed this just by stripping the \x00 from the RQ in my fork -- I'll submit a PR for it if you'd like.

Also, my vim setup runs "go fmt" on save and I noticed it hadn't been run on this repo. I fixed that in a separate commit.

**Comment by pin** [comment]
Mojo, thank you for catching and fixing that, closing!
