### ISSUE TITLE
Please release and tag

### ISSUE THREAD

**Issue by calmh** [pin/tftp#18]
Hi! Thanks for this package. For it to be properly consumable from gb, it would be great if you could create a `v1.0.0` or similar tag on this package (and then continue doing so when making new releases :).

(Background, if you like: http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases)

**Comment by pin** [comment]
@calmh, thanks for suggestion and for useful link!

Here you go: https://github.com/pin/tftp/releases/tag/v2.0.0

Sorry for delay, I've decided to fix OS X build on Travis CI first. It is to be major version 2 because recently there was major API change.
