### ISSUE TITLE
How to get the sent bytes in real time?

### ISSUE THREAD

**Issue by waini1110** [pin/tftp#52]
Thank you for developing such a package. 
I'm using it in my project,but I don't know how to get the sent bytes in real time

**Comment by pin** [comment]
@waini1110, sorry for the slow response!

Maybe just wrap your reader?

```
type CountingReader struct {
    reader    io.Reader
    BytesRead int
}


func (r *CountingReader) Read(p []byte) (n int, err error) {
    n, err = r.reader.Read(p)
    r.BytesRead += n
    return n, err
}
```
(c) https://benjamincongdon.me/blog/2018/04/10/Counting-Scanned-Bytes-in-Go/

Don't forget to synchronize access to `r.BytesRead` I guess!
