### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by shakram02** [pin/tftp#56]
Hello,

can you please release this project as a binary? or a Docker image. Since most tftp servers out there are not very beginner friendly.

Thanks,

**Comment by pin** [comment]
Hi @shakram02!

It is probably possible to do technically, but will have a little use: this is not a complete TFTP server and client, but a library that you could use to build your own custom server or client for some specific purposes as part of some application or system.

This is very basic example: https://github.com/pin/golang-tftp-example

Please feel free to reopen if I'm missing something :)
