### ISSUE TITLE
Is there a Dial with Options support for outbound connections?

### ISSUE THREAD

**Issue by kesavankm** [pin/tftp#57]
If the inbound connections are bound a specific interface (wlan0 vs eth0), how can I instruct the outbound connections to also be bound to this interface?

Thanks for your contribution.

**Comment by 31337Ghost** [comment]
Might it be only the OS decision? In that case outgoing interface could be "set" by adding a specific route in the OS to the client IP address.

**Comment by pin** [comment]
Probably #58 developed by @VictorLowther covers exactly that. Please feel free to reopen if it is not what you need.
