### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by smasher164** [pin/tftp#63]
There have been multiple commits to master since 2.1.0 was released in 2016. Is it possible to cut another one? If it's not backwards compatible, then it could require a major version bump to 3.

Thanks

**Comment by edgood1** [comment]
+1. The 2.1.0 version doesn't include the `RequestTSize` method. I'm having to pull the latest version down with
```go get github.com/pin/tftp@master```

**Comment by pin** [comment]
I've added v2.2.0, which is backward-compatible with previous release. Thank you for your patience and apology for the delay.
